trigger:
  branches: 
    include: 
      - main
      - develop

pool: 
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs: 
    versionSpec: "20.x"

- script: npm install
  displayName: Install deps
  workingDirectory: corecomply-design-system

- script: npm run build-storybook
  displayName: Build Storybook
  workingDirectory: corecomply-design-system

- publish: corecomply-design-system/storybook-static
  artifact: storybook
  displayName: Publish Storybook artifact
