trigger: none

schedules:
- cron: "0 2 * * *"
  displayName: Nightly Figma Sync
  branches: 
    include: 
      - main
  always: true

pool: 
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- task: NodeTool@0
  inputs: 
    versionSpec: "20.x"

- script: npm install
  displayName: Install deps
  workingDirectory: corecomply-design-system

- script: npm run figma:pull
  displayName: Pull Figma assets and tokens
  workingDirectory: corecomply-design-system
  env:
    FIGMA_TOKEN: $(FIGMA_TOKEN)
    FIGMA_FILE_KEY: $(FIGMA_FILE_KEY)

- script: |
    git config user.email "devops-bot@corecomply.local"
    git config user.name "Azure DevOps Bot"
    git add corecomply-design-system/design/icons/svg corecomply-design-system/design/logos/png corecomply-design-system/design/tokens || true
    git commit -m "chore(figma): sync" || echo "No changes"
    git push origin HEAD:$(Build.SourceBranchName) || echo "No push"
  displayName: Commit changes if any

- publish: corecomply-design-system/design
  artifact: figma-design
