import { create } from 'zustand';

export interface Obligation {
  id: string;
  framework?: string;
  category: string;
  title: string;
  description: string;
  source: string;
  jurisdiction: string;
  trigger: string;
  roles: {
    R: string;
    A: string;
    S: string;
    C: string;
    I: string;
  };
  evidence: string;
  controlRef: string;
  status: 'Compliant' | 'Gap' | 'Pending';
  lastReviewed?: string;
  nextReviewDue?: string;
  notes?: string;
  evidenceFiles?: string[];
  evidenceLinks?: string[];
}

interface ObligationsState {
  obligations: Obligation[];
  addObligation: (obligation: Obligation) => void;
  updateObligation: (id: string, updates: Partial<Obligation>) => void;
  deleteObligation: (id: string) => void;
  setStatus: (id: string, status: 'Compliant' | 'Gap' | 'Pending') => void;
  setReviewDates: (id: string, lastReviewed: string, nextReviewDue: string) => void;
  linkEvidence: (id: string, files: string[], links: string[]) => void;
}

// Real Australian Payroll Governance Management System Framework (APGF-MS) obligations data from CSV
const initialObligations: Obligation[] = [
  { id: "OBL-FW-001", category: "Legislation", title: "Issue Fair Work Information Statement (FWIS)", description: "Provide the FWIS to every new employee; retain evidence of delivery (digital or signed).", source: "Fair Work Act 2009; FWO FWIS", jurisdiction: "Commonwealth", trigger: "On hire", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "Employee" }, evidence: "Copy of FWIS version; onboarding checklist; e-sign proof", controlRef: "4.2 Information & Awareness", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-002", category: "Legislation", title: "Issue Casual Employment Information Statement (CEIS) to casuals", description: "Provide CEIS on engagement and after 12 months per FWO guidance.", source: "Fair Work Act; FWO CEIS", jurisdiction: "Commonwealth", trigger: "On casual hire; at 12 months", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "Employee" }, evidence: "CEIS issue log; acknowledgement", controlRef: "4.2 Information & Awareness", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-003", category: "Legislation", title: "Provide Fixed Term Contract Information Statement (FTCIS)", description: "Provide FTCIS when using a fixed-term contract; ensure term limits and exceptions are met.", source: "Fair Work Legislation Amendment (Closing Loopholes) & FWO FTCIS", jurisdiction: "Commonwealth", trigger: "On fixed-term engagement", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "Employee" }, evidence: "FTCIS copy; contract term tracker", controlRef: "5.3 Employment Basis Controls", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-004", category: "Legislation", title: "Maintain compliant payslips", description: "Issue payslips within 1 working day with all mandatory details (period, gross/net, tax, super, leave, etc.).", source: "Fair Work Regulations 2009; FWO Payslips", jurisdiction: "Commonwealth", trigger: "Per pay run", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "Employees" }, evidence: "Payslip template; sample set per period; issue timestamp report", controlRef: "5.8 Payroll Processing", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-005", category: "Legislation", title: "Keep required time & wages records", description: "Maintain time and wages records for required retention period; ensure accessibility and accuracy.", source: "Fair Work Regulations 2009; FWO record-keeping", jurisdiction: "Commonwealth", trigger: "Continuous", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Internal/External Audit" }, evidence: "Record-keeping SOP; retention schedule; access logs", controlRef: "7.2 Records Control", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-006", category: "Legislation", title: "Public holidays handling", description: "Identify public holidays per site and apply correct pay and rostering rules under NES/Award/EA.", source: "Fair Work Act NES + Award/EA; State/Territory gazettes", jurisdiction: "National", trigger: "Per roster; per holiday", roles: { R: "Line Manager", A: "Compliance Owner", S: "Payroll Officer", C: "HR Officer", I: "Employees" }, evidence: "Public holiday register by site; payroll rule mapping", controlRef: "5.1 Rostering", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-007", category: "Legislation", title: "Casual conversion assessments", description: "Assess eligibility and issue notices within required timeframe; capture decisions.", source: "Fair Work Act; FWO guidance", jurisdiction: "Commonwealth", trigger: "At required review points", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "Employee" }, evidence: "Assessment log; notices; outcomes", controlRef: "6.4 Employment Reviews", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-008", category: "Legislation", title: "Annualised wage arrangements controls", description: "If annualised salaries used under an award, configure outer limits, capture time, and perform annual reconciliation/make-good.", source: "Modern Award clauses; FWO", jurisdiction: "Commonwealth", trigger: "Continuous; annual reconciliation", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Line Manager", I: "Employee" }, evidence: "Outer limit config; recon report; make-good payment evidence", controlRef: "6.2 Annualised Wages", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-009", category: "Legislation", title: "Award/EA coverage and classification", description: "Identify applicable Award/EA; assign correct classification level; version-control pay guides.", source: "Modern Awards; Enterprise Agreement", jurisdiction: "Commonwealth", trigger: "On hire; on change", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "Line Manager" }, evidence: "Award map; classification record; pay guide version ref", controlRef: "5.5 Classification", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-FW-010", category: "Legislation", title: "Termination & final pay timing", description: "Calculate notice/redundancy/ETP; pay all entitlements within award/EA/NES timing; apply tax rules.", source: "NES; Award/EA; ATO ETP rules", jurisdiction: "Commonwealth", trigger: "On termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Finance Manager", I: "Employee" }, evidence: "Final pay calc; ETP summary; STP cessation record", controlRef: "5.9 Cessation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-ATO-001", category: "Taxation", title: "Register and operate PAYG Withholding", description: "Register before first payment; withhold per ATO tables; remit via BAS/IAS per remitter status.", source: "ATO PAYG-W", jurisdiction: "Commonwealth", trigger: "Onboarding; per pay; BAS/IAS cycle", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "PAYG registration; BAS/IAS copies; payment receipts", controlRef: "6.5 Tax Reporting", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-ATO-002", category: "Taxation", title: "TFN Declarations collection and lodgement", description: "Collect TFN Declaration; lodge within 14 days; handle TFN under TFN Rule and Privacy Act.", source: "ATO TFN Declaration; Privacy (Tax File Number) Rule", jurisdiction: "Commonwealth", trigger: "On hire; 14 days", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "IT/InfoSec" }, evidence: "TFND copies; ATO receipt; TFN handling SOP", controlRef: "4.4 Onboarding Data", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-ATO-003", category: "Taxation", title: "Single Touch Payroll (Phase 2) reporting", description: "Submit STP pay event on or before payment; use Phase 2 disaggregated earnings and codes; manage errors & finalisation.", source: "ATO STP Phase 2", jurisdiction: "Commonwealth", trigger: "Per pay event; annual finalisation", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "CEO/Board" }, evidence: "STP success receipts; error logs; finalisation report", controlRef: "6.1 STP Controls", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-ATO-004", category: "Taxation", title: "Reportable Fringe Benefits Amounts (RFBA)", description: "Determine RFBA > $2,000 and report grossed-up amounts through STP by finalisation deadlines.", source: "FBT Act; ATO RFBA", jurisdiction: "Commonwealth", trigger: "Annual", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "RFBA workpapers; STP inclusion proof", controlRef: "6.6 RFBA", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-ATO-005", category: "Taxation", title: "Study & training support loans withholding", description: "Apply correct withholding for HELP/SSL/TSL based on declarations and ATO schedules.", source: "ATO tables", jurisdiction: "Commonwealth", trigger: "Per pay", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "Employee" }, evidence: "Declaration copy; tax scale configuration", controlRef: "5.7 Tax Scales", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-ATO-006", category: "Taxation", title: "Working Holiday Maker withholding", description: "Apply WHM tax rates and registration if employing WHM visa holders.", source: "ATO WHM", jurisdiction: "Commonwealth", trigger: "Per pay; on hire", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "Employee" }, evidence: "WHM registration; tax table config", controlRef: "5.7 Tax Scales", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-SUP-001", category: "Superannuation", title: "Calculate and pay Superannuation Guarantee (SG)", description: "Calculate SG at the prescribed rate on ordinary time earnings; pay by quarterly due dates via SuperStream.", source: "Superannuation Guarantee (Administration) Act; ATO", jurisdiction: "Commonwealth", trigger: "Quarterly (by 28th after Qtr end)", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "Employee" }, evidence: "SG calc report; payment file; SuperStream confirmation", controlRef: "6.3 SG Compliance", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-SUP-002", category: "Superannuation", title: "Choice of fund and stapled super process", description: "Offer Standard Choice form; if no valid choice, perform stapled fund check and pay to stapled fund; maintain MySuper compliant default.", source: "ATO stapled super; SG Act", jurisdiction: "Commonwealth", trigger: "On hire; on change", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employee" }, evidence: "Choice forms; stapled check evidence; default fund details", controlRef: "5.6 Super Choice", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-SUP-003", category: "Superannuation", title: "Super eligibility & exceptions handling", description: "Apply SG eligibility rules (e.g., contractors deemed employees, private/domestic work, under-18 hours threshold, etc.)", source: "SG Act; ATO guidance", jurisdiction: "Commonwealth", trigger: "Per engagement; per pay", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Line Manager" }, evidence: "Eligibility assessment; exceptions log", controlRef: "5.6 Super Choice", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-SA-001", category: "Government Deductions", title: "Child Support deductions & remittances", description: "Action binding notices; calculate per schedule; withhold and remit by due dates; respond to variations/cancellations.", source: "Child Support (Registration and Collection) Act; Services Australia", jurisdiction: "Commonwealth", trigger: "Per pay; remittance schedule", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "Employee" }, evidence: "Deduction schedule; remittance proof; notice register", controlRef: "5.10 Child Support", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-SA-002", category: "Government Payments", title: "Paid Parental Leave employer role", description: "Administer employer role where applicable; coordinate with Services Australia; manage offsets with employer-paid leave.", source: "Paid Parental Leave Act; Services Australia", jurisdiction: "Commonwealth", trigger: "On claim; per pay cycle during PPL", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Finance Manager", I: "Employee" }, evidence: "PPL correspondence; payroll configuration", controlRef: "5.12 Parental Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-VEVO-001", category: "Right to Work", title: "Verify work rights (VEVO/citizenship)", description: "Check and retain evidence of right to work at onboarding; monitor visa conditions for restrictions/expiry.", source: "Migration Act; Home Affairs VEVO", jurisdiction: "Commonwealth", trigger: "On hire; periodic for visas", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "Line Manager" }, evidence: "VEVO check log; ID record; monitoring schedule", controlRef: "5.2 Right to Work", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PRIV-001", category: "Privacy", title: "Handle TFNs under TFN Rule", description: "Collect, store, use and destroy TFN data per the Privacy (Tax File Number) Rule 2015.", source: "OAIC TFN Rule 2015", jurisdiction: "Commonwealth", trigger: "Continuous", roles: { R: "IT/InfoSec", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "HR Officer" }, evidence: "TFN handling SOP; access controls; disposal records", controlRef: "7.2 Records Control", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PRIV-002", category: "Privacy", title: "Notifiable Data Breaches (NDB) readiness", description: "Maintain data breach response plan; assess payroll-related breaches; notify OAIC/individuals where required.", source: "Privacy Act; OAIC NDB scheme", jurisdiction: "Commonwealth", trigger: "Continuous; on incident", roles: { R: "IT/InfoSec", A: "Compliance Owner", S: "Legal/IR", C: "CEO/Board", I: "Payroll Officer" }, evidence: "IR playbook; drill records; assessment templates", controlRef: "7.4 Incident Response", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PRIV-003", category: "Privacy", title: "FDV leave confidentiality on payslips", description: "Ensure FDV leave is recorded and displayed to protect confidentiality; restrict access to records.", source: "FWO FDV leave guidance; NES", jurisdiction: "Commonwealth", trigger: "Per leave event", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "IT/InfoSec" }, evidence: "Masked payslip evidence; restricted access logs", controlRef: "4.5 Sensitive Leave Handling", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  // State Payroll Tax obligations (8 states/territories)
  { id: "OBL-PTX-ACT", category: "State Payroll Tax", title: "Payroll tax registration and returns - ACT", description: "Register if wages exceed threshold in ACT; lodge monthly/annual returns; manage grouping and interstate wages apportionment.", source: "ACT Revenue Office", jurisdiction: "ACT", trigger: "Monthly/Annual (per state rules)", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "Registration; returns; payments; grouping analysis", controlRef: "6.7 State Tax", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PTX-NSW", category: "State Payroll Tax", title: "Payroll tax registration and returns - NSW", description: "Register if wages exceed threshold in NSW; lodge monthly/annual returns; manage grouping and interstate wages apportionment.", source: "NSW Revenue Office", jurisdiction: "NSW", trigger: "Monthly/Annual (per state rules)", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "Registration; returns; payments; grouping analysis", controlRef: "6.7 State Tax", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PTX-NT", category: "State Payroll Tax", title: "Payroll tax registration and returns - NT", description: "Register if wages exceed threshold in NT; lodge monthly/annual returns; manage grouping and interstate wages apportionment.", source: "NT Revenue Office", jurisdiction: "NT", trigger: "Monthly/Annual (per state rules)", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "Registration; returns; payments; grouping analysis", controlRef: "6.7 State Tax", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PTX-QLD", category: "State Payroll Tax", title: "Payroll tax registration and returns - QLD", description: "Register if wages exceed threshold in QLD; lodge monthly/annual returns; manage grouping and interstate wages apportionment.", source: "QLD Revenue Office", jurisdiction: "QLD", trigger: "Monthly/Annual (per state rules)", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "Registration; returns; payments; grouping analysis", controlRef: "6.7 State Tax", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PTX-SA", category: "State Payroll Tax", title: "Payroll tax registration and returns - SA", description: "Register if wages exceed threshold in SA; lodge monthly/annual returns; manage grouping and interstate wages apportionment.", source: "SA Revenue Office", jurisdiction: "SA", trigger: "Monthly/Annual (per state rules)", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "Registration; returns; payments; grouping analysis", controlRef: "6.7 State Tax", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PTX-TAS", category: "State Payroll Tax", title: "Payroll tax registration and returns - TAS", description: "Register if wages exceed threshold in TAS; lodge monthly/annual returns; manage grouping and interstate wages apportionment.", source: "TAS Revenue Office", jurisdiction: "TAS", trigger: "Monthly/Annual (per state rules)", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "Registration; returns; payments; grouping analysis", controlRef: "6.7 State Tax", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PTX-VIC", category: "State Payroll Tax", title: "Payroll tax registration and returns - VIC", description: "Register if wages exceed threshold in VIC; lodge monthly/annual returns; manage grouping and interstate wages apportionment.", source: "VIC Revenue Office", jurisdiction: "VIC", trigger: "Monthly/Annual (per state rules)", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "Registration; returns; payments; grouping analysis", controlRef: "6.7 State Tax", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PTX-WA", category: "State Payroll Tax", title: "Payroll tax registration and returns - WA", description: "Register if wages exceed threshold in WA; lodge monthly/annual returns; manage grouping and interstate wages apportionment.", source: "WA Revenue Office", jurisdiction: "WA", trigger: "Monthly/Annual (per state rules)", roles: { R: "Finance Manager", A: "CEO/Board", S: "Payroll Officer", C: "External Accountant", I: "Compliance Owner" }, evidence: "Registration; returns; payments; grouping analysis", controlRef: "6.7 State Tax", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  // Workers' Compensation obligations (8 states/territories)
  { id: "OBL-WC-ACT", category: "Workers' Compensation", title: "Maintain workers' compensation policy - ACT", description: "Hold valid policy for ACT; declare estimated/remuneration wages annually; pay premium; manage claims and return-to-work.", source: "ACT Workers' Compensation Regulator/Insurer", jurisdiction: "ACT", trigger: "Annual; on claims", roles: { R: "HR Officer", A: "CEO/Board", S: "Payroll Officer", C: "Compliance Owner", I: "Finance Manager" }, evidence: "Policy certificate; wage declarations; claim files", controlRef: "6.8 Workers' Compensation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-WC-NSW", category: "Workers' Compensation", title: "Maintain workers' compensation policy - NSW", description: "Hold valid policy for NSW; declare estimated/remuneration wages annually; pay premium; manage claims and return-to-work.", source: "NSW Workers' Compensation Regulator/Insurer", jurisdiction: "NSW", trigger: "Annual; on claims", roles: { R: "HR Officer", A: "CEO/Board", S: "Payroll Officer", C: "Compliance Owner", I: "Finance Manager" }, evidence: "Policy certificate; wage declarations; claim files", controlRef: "6.8 Workers' Compensation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-WC-NT", category: "Workers' Compensation", title: "Maintain workers' compensation policy - NT", description: "Hold valid policy for NT; declare estimated/remuneration wages annually; pay premium; manage claims and return-to-work.", source: "NT Workers' Compensation Regulator/Insurer", jurisdiction: "NT", trigger: "Annual; on claims", roles: { R: "HR Officer", A: "CEO/Board", S: "Payroll Officer", C: "Compliance Owner", I: "Finance Manager" }, evidence: "Policy certificate; wage declarations; claim files", controlRef: "6.8 Workers' Compensation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-WC-QLD", category: "Workers' Compensation", title: "Maintain workers' compensation policy - QLD", description: "Hold valid policy for QLD; declare estimated/remuneration wages annually; pay premium; manage claims and return-to-work.", source: "QLD Workers' Compensation Regulator/Insurer", jurisdiction: "QLD", trigger: "Annual; on claims", roles: { R: "HR Officer", A: "CEO/Board", S: "Payroll Officer", C: "Compliance Owner", I: "Finance Manager" }, evidence: "Policy certificate; wage declarations; claim files", controlRef: "6.8 Workers' Compensation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-WC-SA", category: "Workers' Compensation", title: "Maintain workers' compensation policy - SA", description: "Hold valid policy for SA; declare estimated/remuneration wages annually; pay premium; manage claims and return-to-work.", source: "SA Workers' Compensation Regulator/Insurer", jurisdiction: "SA", trigger: "Annual; on claims", roles: { R: "HR Officer", A: "CEO/Board", S: "Payroll Officer", C: "Compliance Owner", I: "Finance Manager" }, evidence: "Policy certificate; wage declarations; claim files", controlRef: "6.8 Workers' Compensation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-WC-TAS", category: "Workers' Compensation", title: "Maintain workers' compensation policy - TAS", description: "Hold valid policy for TAS; declare estimated/remuneration wages annually; pay premium; manage claims and return-to-work.", source: "TAS Workers' Compensation Regulator/Insurer", jurisdiction: "TAS", trigger: "Annual; on claims", roles: { R: "HR Officer", A: "CEO/Board", S: "Payroll Officer", C: "Compliance Owner", I: "Finance Manager" }, evidence: "Policy certificate; wage declarations; claim files", controlRef: "6.8 Workers' Compensation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-WC-VIC", category: "Workers' Compensation", title: "Maintain workers' compensation policy - VIC", description: "Hold valid policy for VIC; declare estimated/remuneration wages annually; pay premium; manage claims and return-to-work.", source: "VIC Workers' Compensation Regulator/Insurer", jurisdiction: "VIC", trigger: "Annual; on claims", roles: { R: "HR Officer", A: "CEO/Board", S: "Payroll Officer", C: "Compliance Owner", I: "Finance Manager" }, evidence: "Policy certificate; wage declarations; claim files", controlRef: "6.8 Workers' Compensation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-WC-WA", category: "Workers' Compensation", title: "Maintain workers' compensation policy - WA", description: "Hold valid policy for WA; declare estimated/remuneration wages annually; pay premium; manage claims and return-to-work.", source: "WA Workers' Compensation Regulator/Insurer", jurisdiction: "WA", trigger: "Annual; on claims", roles: { R: "HR Officer", A: "CEO/Board", S: "Payroll Officer", C: "Compliance Owner", I: "Finance Manager" }, evidence: "Policy certificate; wage declarations; claim files", controlRef: "6.8 Workers' Compensation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  // Long Service Leave obligations (8 states/territories)
  { id: "OBL-LSL-ACT", category: "Long Service Leave", title: "LSL accrual and payment compliance - ACT", description: "Apply LSL legislation in ACT (qualifying service, accrual method, payment rules).", source: "ACT LSL Act", jurisdiction: "ACT", trigger: "Continuous; on request/termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employees" }, evidence: "Accrual schedule; payment calculations; policy", controlRef: "5.13 Long Service Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-LSL-NSW", category: "Long Service Leave", title: "LSL accrual and payment compliance - NSW", description: "Apply LSL legislation in NSW (qualifying service, accrual method, payment rules).", source: "NSW LSL Act", jurisdiction: "NSW", trigger: "Continuous; on request/termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employees" }, evidence: "Accrual schedule; payment calculations; policy", controlRef: "5.13 Long Service Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-LSL-NT", category: "Long Service Leave", title: "LSL accrual and payment compliance - NT", description: "Apply LSL legislation in NT (qualifying service, accrual method, payment rules).", source: "NT LSL Act", jurisdiction: "NT", trigger: "Continuous; on request/termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employees" }, evidence: "Accrual schedule; payment calculations; policy", controlRef: "5.13 Long Service Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-LSL-QLD", category: "Long Service Leave", title: "LSL accrual and payment compliance - QLD", description: "Apply LSL legislation in QLD (qualifying service, accrual method, payment rules).", source: "QLD LSL Act", jurisdiction: "QLD", trigger: "Continuous; on request/termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employees" }, evidence: "Accrual schedule; payment calculations; policy", controlRef: "5.13 Long Service Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-LSL-SA", category: "Long Service Leave", title: "LSL accrual and payment compliance - SA", description: "Apply LSL legislation in SA (qualifying service, accrual method, payment rules).", source: "SA LSL Act", jurisdiction: "SA", trigger: "Continuous; on request/termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employees" }, evidence: "Accrual schedule; payment calculations; policy", controlRef: "5.13 Long Service Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-LSL-TAS", category: "Long Service Leave", title: "LSL accrual and payment compliance - TAS", description: "Apply LSL legislation in TAS (qualifying service, accrual method, payment rules).", source: "TAS LSL Act", jurisdiction: "TAS", trigger: "Continuous; on request/termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employees" }, evidence: "Accrual schedule; payment calculations; policy", controlRef: "5.13 Long Service Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-LSL-VIC", category: "Long Service Leave", title: "LSL accrual and payment compliance - VIC", description: "Apply LSL legislation in VIC (qualifying service, accrual method, payment rules).", source: "VIC LSL Act", jurisdiction: "VIC", trigger: "Continuous; on request/termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employees" }, evidence: "Accrual schedule; payment calculations; policy", controlRef: "5.13 Long Service Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-LSL-WA", category: "Long Service Leave", title: "LSL accrual and payment compliance - WA", description: "Apply LSL legislation in WA (qualifying service, accrual method, payment rules).", source: "WA LSL Act", jurisdiction: "WA", trigger: "Continuous; on request/termination", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Legal/IR", I: "Employees" }, evidence: "Accrual schedule; payment calculations; policy", controlRef: "5.13 Long Service Leave", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  // Portable LSL obligations (3)
  { id: "OBL-PLSL-QLD-BC", category: "Portable LSL", title: "Building & Construction Portable LSL - QLD", description: "Register eligible employers/workers; submit returns and pay levies to the portable LSL scheme.", source: "QLeave (QLD)", jurisdiction: "QLD", trigger: "Per scheme schedule", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "Line Manager" }, evidence: "Scheme registration; returns; payments", controlRef: "5.11 Portable LSL", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PLSL-VIC-CCS", category: "Portable LSL", title: "Community Services/Contract Cleaning/Security Portable LSL - VIC", description: "Register and report eligible workers; pay levies to the Victorian Portable LSL Authority.", source: "Victorian Portable LSL Authority", jurisdiction: "VIC", trigger: "Per scheme schedule", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "Line Manager" }, evidence: "Registration; returns; levy payments", controlRef: "5.11 Portable LSL", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-PLSL-ACT-MULTI", category: "Portable LSL", title: "Portable LSL schemes - ACT", description: "Register relevant workers (cleaning, community, security, construction); lodge returns and pay levies.", source: "ACT Portable LSL Authority", jurisdiction: "ACT", trigger: "Per scheme schedule", roles: { R: "Payroll Officer", A: "Finance Manager", S: "HR Officer", C: "Compliance Owner", I: "Line Manager" }, evidence: "Registration; returns; levy payments", controlRef: "5.11 Portable LSL", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  // Operations obligations
  { id: "OBL-TNA-001", category: "Operations", title: "Rostering: ordinary hours, breaks, span", description: "Configure rosters to meet NES/Award span of hours, breaks, and maximum weekly hours.", source: "NES + Award/EA", jurisdiction: "Commonwealth", trigger: "Per roster change", roles: { R: "Line Manager", A: "Compliance Owner", S: "Payroll Officer", C: "HR Officer", I: "Employees" }, evidence: "Roster policy; scheduling evidence", controlRef: "5.1 Rostering", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-TNA-002", category: "Operations", title: "Time capture & approvals", description: "Capture accurate time (incl. remote work & overtime) with approval trail; prohibit unrecorded work.", source: "Award/EA; FWA", jurisdiction: "Commonwealth", trigger: "Per shift; per pay", roles: { R: "Line Manager", A: "Compliance Owner", S: "Payroll Officer", C: "HR Officer", I: "Employees" }, evidence: "Timesheets; approvals; exception reports", controlRef: "5.1 Rostering", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  // Remuneration obligations
  { id: "OBL-REM-001", category: "Remuneration", title: "Annual minimum wage/Award rate updates", description: "Apply FWC annual wage decision and award updates; communicate and backpay where required.", source: "FWC Annual Wage Review; FWO pay guides", jurisdiction: "Commonwealth", trigger: "Annual (July)", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "Finance Manager" }, evidence: "Rate change log; pay guide version control; backpay calc", controlRef: "5.5 Classification", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-REM-002", category: "Remuneration", title: "Reclassification & progression", description: "Process promotions/reclassifications per Award/EA rules; update rate and anniversary dates.", source: "Award/EA", jurisdiction: "Commonwealth", trigger: "On change", roles: { R: "HR Officer", A: "Compliance Owner", S: "Payroll Officer", C: "Line Manager", I: "Finance Manager" }, evidence: "Approval record; payroll update evidence", controlRef: "5.5 Classification", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  // Governance obligations
  { id: "OBL-AUD-001", category: "Governance", title: "Internal payroll control testing", description: "Test operating effectiveness of key controls (SoD, approvals, reconciliations) and record findings/actions.", source: "APGF-MS; ISO-style management system", jurisdiction: "National", trigger: "Quarterly/Annual", roles: { R: "Compliance Owner", A: "CEO/Board", S: "Internal Audit", C: "Finance Manager", I: "Payroll Officer" }, evidence: "Test plans; results; action register", controlRef: "9.1 Performance Evaluation", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-AUD-002", category: "Governance", title: "Annualised wages reconciliation & make-good", description: "Perform annual reconciliation for annualised wage staff; rectify any shortfall; document sign-off.", source: "Award clauses; FWO", jurisdiction: "Commonwealth", trigger: "Annual", roles: { R: "Payroll Officer", A: "Compliance Owner", S: "HR Officer", C: "Line Manager", I: "Employees" }, evidence: "Reconciliation report; make-good payment proof", controlRef: "6.2 Annualised Wages", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-AUD-003", category: "Governance", title: "Regulatory change monitoring", description: "Monitor FWO/ATO/State updates; update obligations register and communicate changes to owners.", source: "Regulatory bulletins; gazettes", jurisdiction: "National", trigger: "Monthly; on change", roles: { R: "Compliance Owner", A: "CEO/Board", S: "Legal/IR", C: "Payroll Officer", I: "HR Officer" }, evidence: "Change log; versioned register; comms records", controlRef: "10.1 Improvement", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  // Policy obligations
  { id: "OBL-POL-001", category: "Policy", title: "Payroll policy & governance", description: "Maintain payroll policy defining scope, responsibilities, RASCI, and escalation/rectification processes.", source: "Company policy; APGF-MS", jurisdiction: "National", trigger: "Annual review", roles: { R: "Compliance Owner", A: "CEO/Board", S: "Payroll Officer", C: "HR Officer", I: "All Staff" }, evidence: "Approved policy; review log", controlRef: "2.3 Leadership & Policy", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
  { id: "OBL-POL-002", category: "Policy", title: "Privacy & access policy for payroll data", description: "Define access roles, least privilege, encryption, and transmission controls for payroll PII/TFN data.", source: "Privacy Act; TFN Rule; InfoSec policy", jurisdiction: "National", trigger: "Annual review", roles: { R: "IT/InfoSec", A: "Compliance Owner", S: "Payroll Officer", C: "Legal/IR", I: "HR Officer" }, evidence: "Access matrix; audit logs; DLP config", controlRef: "7.2 Records & Security", status: "Pending", evidenceFiles: [], evidenceLinks: [] },
];

export const useObligationsStore = create<ObligationsState>((set) => ({
  obligations: initialObligations,

  addObligation: (obligation) =>
    set((state) => ({
      obligations: [...state.obligations, obligation],
    })),

  updateObligation: (id, updates) =>
    set((state) => ({
      obligations: state.obligations.map((obl) =>
        obl.id === id ? { ...obl, ...updates } : obl
      ),
    })),

  deleteObligation: (id) =>
    set((state) => ({
      obligations: state.obligations.filter((obl) => obl.id !== id),
    })),

  setStatus: (id, status) =>
    set((state) => ({
      obligations: state.obligations.map((obl) =>
        obl.id === id ? { ...obl, status } : obl
      ),
    })),

  setReviewDates: (id, lastReviewed, nextReviewDue) =>
    set((state) => ({
      obligations: state.obligations.map((obl) =>
        obl.id === id ? { ...obl, lastReviewed, nextReviewDue } : obl
      ),
    })),

  linkEvidence: (id, files, links) =>
    set((state) => ({
      obligations: state.obligations.map((obl) =>
        obl.id === id
          ? {
              ...obl,
              evidenceFiles: [...(obl.evidenceFiles || []), ...files],
              evidenceLinks: [...(obl.evidenceLinks || []), ...links],
            }
          : obl
      ),
    })),
}));
